### PR TITLE
Connect to api

### PR DESCRIPTION
**Pull request by erickma1**
In this milestone, I achieved the following;

- Made use of the Bookstore API as my backend
- Used axios with createAsyncThunk to make my HTTP requests to the backend
- Fetch my books from the Bookstore API after the component has rendered

### CODE REVIEW

**Review by DammyShittu — COMMENTED** [review]
Hi @erickma1,

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

### Kindly add a live demo link or remove everything related to live demo from the readme, including the header link.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by erickma1** [comment]
Remove live demo link from README

**Comment by erickma1** [comment]
Remove live demo link from README

**Review by topeogunleye — APPROVED** [review]
Hi @erickma1, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

dwayne-the-rock

## (Highlights) Good Points: 💪 

#### **1. Use of createAsyncThunk and Implementation of fetchBooks 🌟**
   - 👏 You’ve correctly imported `createAsyncThunk` and efficiently created the action creator called `fetchBooks`. The use of `createAsyncThunk` showcases an understanding of asynchronous actions in Redux.
   - 🕵️ Your verification and implementation of the HTTP request using Axios are in compliance with the project requirements, and it’s clear that you are making all HTTP requests using Axios.

```javascript
import { createAsyncThunk, createSlice } from "@reduxjs/toolkit"
import axios from "axios"

export const fetchBooks = createAsyncThunk("books/fetchBooks", async () => {
  // Correctly Making HTTP request
})
```

#### **2. Proper Usage of useEffect Hook in <BookList> Component 📚**
   - 🌿 The use of the `useEffect` hook when dispatching the `fetchBooks` function in your `<BookList>` component is correctly implemented, ensuring the appropriate lifecycle and state management of the component.

```javascript
function BookList() {
  // Correct dispatch of fetchBooks inside useEffect
  useEffect(() => {
    dispatch(fetchBooks())
  }, [])
}
```

#### **3. Refactoring of addBook & removeBook Methods 🛠️**
   - 🔄 Your refactoring of `addBook` and `removeBook` to return a promise and automatically dispatch actions that update the state is commendable. This indicates a good grasp of Redux Thunk and async operations in Redux.

#### **4. Functionality & User Experience 🖥️**
   - 🚀 You’ve maintained the integrity of `addBook` and `removeBook` features, and they work as expected. A practical test of the application in the browser showed everything functioning smoothly.

### Conclusion 🌟

Well done on crafting a well-structured and functional project, with a solid understanding of async operations in Redux showcased. Keep up the excellent work on ensuring each feature is optimized and that your code remains clean and well-organized. Great job! 🎉💻

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
- Nothing to mention.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
